# Generated by Django 2.0.13 on 2022-03-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailinglist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriber',
            new_name='Subscriber',
        ),
    ]
